### ISSUE TITLE
Trilinos and TPL status

### ISSUE THREAD

**Issue by spdomin** [NaluCFD/Nalu#14]
This is a live update on the status of Trilinos and other TPL builds/versions.

**Comment by spdomin** [comment]
@core 

10/13/2016 NaluRtest
PROCESS FAILED
NaluCFD/Nalu SHA1: 636a6744e60f9c730dc540aa59baf9d8605e0011
Trilinos SHA1: 46a01d623c988b686e9af23e2eda920a2aa51de8

/scratch/spdomin/nightlyBuildAndTest/Nalu/include/LinearSolverTypes.h:13,
                 from /scratch/spdomin/nightlyBuildAndTest/Nalu/include/LinearSolver.h:12,
                 from /scratch/spdomin/nightlyBuildAndTest/Nalu/src/LinearSolvers.C:10:
/home/spdomin/gitHubWork/scratch_build/install/gcc4.8.5/Trilinos_nightly_release/include/Kokkos_Sparse_impl_spmv.hpp:53:43: fatal error: TpetraKernels_ETIHelperMacros.h: No such file or directory
 #include "TpetraKernels_ETIHelperMacros.h"

**Comment by spdomin** [comment]
Develop is now working... https://github.com/trilinos/Trilinos/issues/703

10/14/2016
Rtest Begin: 
..periodic3dElemNp1........... PASSED:  4.7  s 
Rtest End
NaluCFD/Nalu SHA1: 636a6744e60f9c730dc540aa59baf9d8605e0011
Trilinos/master SHA1: c89b07a90b1d21f56e8714c1cfe9274c058ba042

**Comment by spdomin** [comment]
Bad test suite as of Trilinos SHA1:

commit 5320963fbe2ec9aeba1dc62871e4be4f44961970
Author: Tobias Wiesner <tawiesn@sandia.gov>
Date:   Wed Oct 19 14:43:41 2016 -0600

Last good:

NaluCFD/Nalu SHA1: d2adbe82d786c3ac8fa9221730788923a6a184f9
Trilinos/master SHA1: 12fd285b28abeb7336a8d4f17913819b9ce7015b

**Comment by spdomin** [comment]
@jhux2 and @srajama1 could one of you perform this bisect? There are many code states of Trilinos between the two states of SHA1 (good and bad) that either do not configure or die to build errors.

**Comment by spdomin** [comment]
31d1a077ad748d89f227c359c9ebdb1b6fe40cbf is the first bad commit
commit 31d1a077ad748d89f227c359c9ebdb1b6fe40cbf
Author: Tobias Wiesner <tawiesn@sandia.gov>
Here is the culprit...

Date:   Mon Oct 17 12:29:53 2016 -0600

    Ifpack: introduce optimized SGS algorithm for 1 rhs only.
    
    In most cases we have only one rhs vector. Avoiding double indices saves
    approximately 25-30% iteration time.

:040000 040000 90b1d9d2092ca94ff87580dd29b0a898950f8fda d66773473e928c43da31f8b5e9e1788f82b471fa M	packages

**Comment by spdomin** [comment]
Here is the current status: https://github.com/trilinos/Trilinos/issues/725

**Comment by spdomin** [comment]
@NaluCFD/core, I just added Nalu.wiki instructions to building boost 1.60.0. Moving up to this version removes the warnings discussed at the stand-up yesterday.

**Comment by spdomin** [comment]
@NaluCFD/core, a new version of STK has just been pushed to Trilinos develop. I think that there have been a couple of API changes in STK that will break the current NaluCFD master code base. After the nightly tests run tonight (or fail) I will push something tomorrow. At that point, we will all need to update Trilinos.

**Comment by alanw0** [comment]
@spdomin if any code-changes required by the API changes are not obvious, shoot me an email and I'll let you know what it means or what needs to be done. I'm not aware of anything major...

**Comment by spdomin** [comment]
@alanw0, we have issues in the promotion of the low to high order scheme. Specifically, issues of bulkData being const and the new one about protected:

In file included from /home/spdomin/gitHubWork/scratch_build/install/gcc4.8.5/Trilinos_stable_release/include/stk_mesh/base/FieldBase.hpp:40:0,
                 from /home/spdomin/gitHubWork/Nalu/include/element_promotion/PromoteElement.h:10,
                 from /home/spdomin/gitHubWork/Nalu/src/element_promotion/PromoteElement.C:8:
/home/spdomin/gitHubWork/scratch_build/install/gcc4.8.5/Trilinos_stable_release/include/stk_mesh/base/BulkData.hpp: In function âvoid sierra::nalu::promotion::internal::create_nodes_for_connectivity_map(stk::mesh::BulkData&, const ConnectivityMap&)â:
/home/spdomin/gitHubWork/scratch_build/install/gcc4.8.5/Trilinos_stable_release/include/stk_mesh/base/BulkData.hpp:845:10: error: âstk::mesh::Entity stk::mesh::BulkData::declare_entity(stk::mesh::EntityRank, stk::mesh::EntityId)â is protected
   Entity declare_entity( EntityRank ent_rank , EntityId ent_id);// Mod Mark
          ^
/home/spdomin/gitHubWork/Nalu/src/element_promotion/PromoteElement.C:412:80: error: within this context
       stk::mesh::Entity node = bulk.declare_entity(stk::topology::NODE_RANK, id);
                                                                                ^
@rcknaus is looking at it, so you can coordinate with him.

**Comment by alanw0** [comment]
For declare_entity, there is a public one that takes a part vector as the last argument. So just pass an empty one like this: stk::mesh::PartVector{}.

For the const issue, I think think you can make the  nalu class constructor take bulkdata as nonconst, and call generate_new_ids on that, but the nalu class can still store a const reference to the bulkdata for use in other places.



On Mar 30, 2017, at 4:21 PM, Stefan P. Domino <notifications@github.com<mailto:notifications@github.com>> wrote:


@alanw0<https://github.com/alanw0>, we have issues in the promotion of the low to high order scheme. Specifically, issues of bulkData being const and the new one about protected:

In file included from /home/spdomin/gitHubWork/scratch_build/install/gcc4.8.5/Trilinos_stable_release/include/stk_mesh/base/FieldBase.hpp:40:0,
from /home/spdomin/gitHubWork/Nalu/include/element_promotion/PromoteElement.h:10,
from /home/spdomin/gitHubWork/Nalu/src/element_promotion/PromoteElement.C:8:
/home/spdomin/gitHubWork/scratch_build/install/gcc4.8.5/Trilinos_stable_release/include/stk_mesh/base/BulkData.hpp: In function ???void sierra::nalu::promotion::internal::create_nodes_for_connectivity_map(stk::mesh::BulkData&, const ConnectivityMap&)???:
/home/spdomin/gitHubWork/scratch_build/install/gcc4.8.5/Trilinos_stable_release/include/stk_mesh/base/BulkData.hpp:845:10: error: ???stk::mesh::Entity stk::mesh::BulkData::declare_entity(stk::mesh::EntityRank, stk::mesh::EntityId)??? is protected
Entity declare_entity( EntityRank ent_rank , EntityId ent_id);// Mod Mark
^
/home/spdomin/gitHubWork/Nalu/src/element_promotion/PromoteElement.C:412:80: error: within this context
stk::mesh::Entity node = bulk.declare_entity(stk::topology::NODE_RANK, id);
^
@rcknaus<https://github.com/rcknaus> is looking at it, so you can coordinate with him.

-

**Comment by spdomin** [comment]
@sayerhs @rcknaus @jrood-nrel there is a new diff in the repos. You three are the only team members who touched code in the past three days. I need someone to perform a bisect. 

There is a possibility that this is due to the Trilinos code base and possibly a false positive - not sure. 

14/66 Test #46: nonIsoNonUniformElemOpenJet ......***Failed   73.84 sec
..nonIsoNonUniformElemOpenJet........... FAILED:  72.4160  s  max diff:  .00000000021757771000094621328263

Bad sha1:

NaluCFD/Nalu SHA1: ebc179773df87195f43b3871a17faf61d05ed652
Trilinos/develop SHA1: bd80ed74a3c8e8741d0994751ec2e2aceb6b704e
